"""
backtest.py -- FTSE 1BN/1BP Backtester
==============================================================================

Runs Tom Hougaard's First Bar Negative / First Bar Positive strategy
over historical 5-min FTSE data.

Usage:
    python -m ftse_bot.backtest                    Full backtest + summary
    python -m ftse_bot.backtest --situational      Breakdown by bar type, day, etc.
    python -m ftse_bot.backtest --export           Export trades to CSV
    python -m ftse_bot.backtest --charts           Generate equity/drawdown charts
    python -m ftse_bot.backtest --month 2025-06    Filter to specific month

Data:
    Reads from data/ftse/ftse_rth.parquet (RTH bars)
    and data/ftse/ftse_all.parquet (all-hours, for pre-market bar)
    Generated by fetch_ftse.py
"""

import sys
import os
import csv
import logging
from datetime import datetime, date, time as dtime
from collections import defaultdict
from dataclasses import dataclass, field

import pandas as pd
import numpy as np

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger("FTSE_BT")

DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "data", "ftse")


# ==============================================================================
#  DATA LOADING
# ==============================================================================

def load_data() -> tuple[pd.DataFrame | None, pd.DataFrame | None]:
    """Load cached FTSE data from parquet files."""
    rth_path = os.path.join(DATA_DIR, "ftse_rth.parquet")
    all_path = os.path.join(DATA_DIR, "ftse_all.parquet")

    rth_df = None
    all_df = None

    if os.path.exists(all_path):
        all_df = pd.read_parquet(all_path)
        if all_df.index.tz is None:
            all_df.index = all_df.index.tz_localize("Europe/London")
        logger.info(f"Loaded all-hours data: {len(all_df)} bars")

    if os.path.exists(rth_path):
        rth_df = pd.read_parquet(rth_path)
        if rth_df.index.tz is None:
            rth_df.index = rth_df.index.tz_localize("Europe/London")
        logger.info(f"Loaded RTH data: {len(rth_df)} bars")

    # If we only have all-hours, use that for everything
    if rth_df is None and all_df is not None:
        rth_df = all_df
        logger.info("Using all-hours data as main dataset")

    return rth_df, all_df


# ==============================================================================
#  DATA CLASSES
# ==============================================================================

@dataclass
class Trade:
    date:          str = ""
    day_of_week:   str = ""
    bar_type:      str = ""        # 1BN, 1BP
    direction:     str = ""        # LONG, SHORT
    entry_price:   float = 0.0
    exit_price:    float = 0.0
    pnl_pts:       float = 0.0
    mfe_pts:       float = 0.0
    mae_pts:       float = 0.0
    held_bars:     int = 0
    held_to_close: bool = False

    # Stop management
    stop_phase:    str = ""        # INITIAL, BREAKEVEN, TRAILING
    bar_width:     float = 0.0
    stake:         float = 1.0

    # Bar data
    bar_open:      float = 0.0
    bar_high:      float = 0.0
    bar_low:       float = 0.0
    bar_close:     float = 0.0

    # Situational
    prev_day_dir:  str = ""        # UP / DOWN
    gap_dir:       str = ""        # GAP_UP / GAP_DOWN / FLAT
    gap_size:      float = 0.0


@dataclass
class DayResult:
    date:          str = ""
    trade_date:    date = None
    day_of_week:   str = ""
    bar_type:      str = ""
    bar_width:     float = 0.0
    bar_open:      float = 0.0
    bar_high:      float = 0.0
    bar_low:       float = 0.0
    bar_close:     float = 0.0
    buy_level:     float = 0.0
    sell_level:    float = 0.0
    stake:         float = 1.0
    gap_dir:       str = ""
    gap_size:      float = 0.0
    trades:        list = field(default_factory=list)
    total_pnl:     float = 0.0
    triggered:     bool = False
    skipped:       bool = False      # Doji skip


# ==============================================================================
#  STRATEGY HELPERS
# ==============================================================================

BUFFER_PTS = 1.0
BAR_WIDTH_THRESHOLD = 30.0
BREAKEVEN_TRIGGER = 10.0
STAKE_PER_POINT = 1.0


def classify_bar(o: float, h: float, l: float, c: float) -> str:
    """Classify the first 5-min bar."""
    if c < o:
        return "1BN"
    elif c > o:
        return "1BP"
    return "DOJI"


def classify_gap(prev_close: float, today_open: float) -> tuple[str, float]:
    if prev_close == 0:
        return "FLAT", 0
    gap = round(today_open - prev_close, 1)
    if gap > 10:
        return "GAP_UP", gap
    elif gap < -10:
        return "GAP_DOWN", gap
    return "FLAT", gap


# ==============================================================================
#  BACKTEST ENGINE
# ==============================================================================

def run_backtest(
    df: pd.DataFrame,
    doji_action: str = "SKIP",
    buffer_pts: float = BUFFER_PTS,
    bar_width_threshold: float = BAR_WIDTH_THRESHOLD,
    breakeven_trigger: float = BREAKEVEN_TRIGGER,
    stake_per_point: float = STAKE_PER_POINT,
) -> list[DayResult]:
    """
    Run 1BN/1BP backtest over all trading days.

    For each day:
      1. Find the 08:00-08:05 bar
      2. Classify as 1BN / 1BP / DOJI
      3. Determine entry levels + stop
      4. Simulate fills on subsequent bars
      5. Manage stop: INITIAL -> BREAKEVEN -> TRAILING
      6. Hard close at 16:30 if still open
    """
    results = []
    prev_close = 0.0

    # Group by trading day
    trading_days = sorted(set(df.index.date))
    logger.info(f"Backtesting {len(trading_days)} trading days...")

    for trade_date in trading_days:
        day_df = df[df.index.date == trade_date]
        if len(day_df) < 5:
            prev_close = day_df.iloc[-1]["Close"] if not day_df.empty else prev_close
            continue

        day_name = trade_date.strftime("%A")

        # Skip weekends (shouldn't be in data, but just in case)
        if trade_date.weekday() >= 5:
            continue

        # Find the 08:00 bar (covers 08:00-08:05)
        first_bar = None
        for idx, row in day_df.iterrows():
            if idx.hour == 8 and idx.minute == 0:
                first_bar = row
                break
            # Some feeds label by bar close time
            if idx.hour == 8 and idx.minute == 5:
                first_bar = row
                break
            # Some feeds use 07:55 for the bar ending at 08:00
            # Try the first bar at or after 08:00
            if idx.hour >= 8 and first_bar is None:
                first_bar = row
                break

        if first_bar is None:
            prev_close = day_df.iloc[-1]["Close"] if not day_df.empty else prev_close
            continue

        o = round(first_bar["Open"], 1)
        h = round(first_bar["High"], 1)
        l = round(first_bar["Low"], 1)
        c = round(first_bar["Close"], 1)
        width = round(h - l, 1)

        bar_type = classify_bar(o, h, l, c)

        # Gap
        gap_dir, gap_size = classify_gap(prev_close, o) if prev_close > 0 else ("FLAT", 0)

        # Previous day direction
        prev_day_dir = ""
        if prev_close > 0 and not day_df.empty:
            prev_day_dir = "UP" if day_df.iloc[0]["Open"] > prev_close else "DOWN"

        # Stake sizing
        stake = stake_per_point
        if width > bar_width_threshold:
            stake = round(stake_per_point / 2, 2)

        # Setup day result
        day_result = DayResult(
            date=str(trade_date), trade_date=trade_date,
            day_of_week=day_name, bar_type=bar_type,
            bar_width=width, bar_open=o, bar_high=h, bar_low=l, bar_close=c,
            stake=stake, gap_dir=gap_dir, gap_size=gap_size,
        )

        # Handle doji
        resolved_type = bar_type
        if bar_type == "DOJI":
            if doji_action == "SKIP":
                day_result.skipped = True
                results.append(day_result)
                prev_close = day_df.iloc[-1]["Close"]
                continue
            elif doji_action == "TREAT_AS_1BN":
                resolved_type = "1BN"
            elif doji_action == "TREAT_AS_1BP":
                resolved_type = "1BP"

        # Entry levels
        buy_level = round(l - buffer_pts, 1)   # Buy stop below bar low
        sell_level = round(h + buffer_pts, 1)   # Sell stop above bar high

        day_result.buy_level = buy_level
        day_result.sell_level = sell_level

        # Determine which orders to place
        # 1BN: buy stop below AND sell stop above (OCO)
        # 1BP: sell stop below only
        if resolved_type == "1BN":
            place_buy = True
            place_sell = True
        else:  # 1BP
            place_buy = False
            place_sell = True
            # 1BP: sell stop is below the bar low
            sell_level = buy_level  # sell below bar low

        # Get post-bar candles (08:05 onwards until 16:30)
        first_bar_idx = day_df.index.get_loc(first_bar.name)
        if isinstance(first_bar_idx, slice):
            first_bar_idx = first_bar_idx.start
        post_bars = list(day_df.iloc[first_bar_idx + 1:].iterrows())

        # Filter to session (up to 16:30)
        session_bars = []
        for idx, row in post_bars:
            if idx.hour > 16 or (idx.hour == 16 and idx.minute > 25):
                break
            session_bars.append((idx, row))

        # Simulate order execution
        direction = None
        entry_price = 0.0
        initial_stop = 0.0
        trail_stop = 0.0
        stop_phase = "INITIAL"
        mfe = 0.0
        mae = 0.0
        entry_bar_idx = 0
        max_price = 0.0  # For trailing

        for i, (idx, row) in enumerate(session_bars):
            # -- Check for entry --
            if direction is None:
                triggered = False

                if place_buy and row["High"] >= buy_level and place_sell and row["Low"] <= sell_level:
                    # Both could trigger on same bar -- use open direction
                    if abs(row["Open"] - buy_level) < abs(row["Open"] - sell_level):
                        direction = "LONG"
                        entry_price = buy_level
                    else:
                        direction = "SHORT"
                        entry_price = sell_level
                    triggered = True
                elif place_buy and row["High"] >= buy_level:
                    direction = "LONG"
                    entry_price = buy_level
                    triggered = True
                elif place_sell and row["Low"] <= sell_level:
                    direction = "SHORT"
                    entry_price = sell_level
                    triggered = True

                if triggered:
                    if direction == "LONG":
                        initial_stop = round(entry_price - width, 1)
                    else:
                        initial_stop = round(entry_price + width, 1)
                    trail_stop = initial_stop
                    stop_phase = "INITIAL"
                    mfe = 0.0
                    mae = 0.0
                    max_price = entry_price
                    entry_bar_idx = i
                    continue

            # -- Manage position --
            if direction == "LONG":
                bar_mfe = row["High"] - entry_price
                bar_mae = entry_price - row["Low"]
                mfe = max(mfe, bar_mfe)
                mae = max(mae, bar_mae)
                max_price = max(max_price, row["High"])

                profit = row["High"] - entry_price

                # Phase transitions
                if stop_phase == "INITIAL" and profit >= breakeven_trigger:
                    stop_phase = "BREAKEVEN"
                    trail_stop = entry_price

                if stop_phase == "BREAKEVEN":
                    # Start trailing
                    new_stop = round(max_price - width, 1)
                    if new_stop > trail_stop:
                        trail_stop = new_stop
                        stop_phase = "TRAILING"

                if stop_phase == "TRAILING":
                    new_stop = round(max_price - width, 1)
                    if new_stop > trail_stop:
                        trail_stop = new_stop

                # Stop check
                if row["Low"] <= trail_stop:
                    pnl = round(trail_stop - entry_price, 1)
                    trade = Trade(
                        date=str(trade_date), day_of_week=day_name,
                        bar_type=resolved_type, direction="LONG",
                        entry_price=entry_price, exit_price=trail_stop,
                        pnl_pts=pnl, mfe_pts=round(mfe, 1), mae_pts=round(mae, 1),
                        held_bars=i - entry_bar_idx, stop_phase=stop_phase,
                        bar_width=width, stake=stake,
                        bar_open=o, bar_high=h, bar_low=l, bar_close=c,
                        prev_day_dir=prev_day_dir, gap_dir=gap_dir, gap_size=gap_size,
                    )
                    day_result.trades.append(trade)
                    direction = None  # Only 1 trade per day

            elif direction == "SHORT":
                bar_mfe = entry_price - row["Low"]
                bar_mae = row["High"] - entry_price
                mfe = max(mfe, bar_mfe)
                mae = max(mae, bar_mae)
                max_price = min(max_price if max_price < entry_price else row["Low"], row["Low"])

                profit = entry_price - row["Low"]

                if stop_phase == "INITIAL" and profit >= breakeven_trigger:
                    stop_phase = "BREAKEVEN"
                    trail_stop = entry_price

                if stop_phase == "BREAKEVEN":
                    new_stop = round(max_price + width, 1)
                    if new_stop < trail_stop:
                        trail_stop = new_stop
                        stop_phase = "TRAILING"

                if stop_phase == "TRAILING":
                    new_stop = round(max_price + width, 1)
                    if new_stop < trail_stop:
                        trail_stop = new_stop

                if row["High"] >= trail_stop:
                    pnl = round(entry_price - trail_stop, 1)
                    trade = Trade(
                        date=str(trade_date), day_of_week=day_name,
                        bar_type=resolved_type, direction="SHORT",
                        entry_price=entry_price, exit_price=trail_stop,
                        pnl_pts=pnl, mfe_pts=round(mfe, 1), mae_pts=round(mae, 1),
                        held_bars=i - entry_bar_idx, stop_phase=stop_phase,
                        bar_width=width, stake=stake,
                        bar_open=o, bar_high=h, bar_low=l, bar_close=c,
                        prev_day_dir=prev_day_dir, gap_dir=gap_dir, gap_size=gap_size,
                    )
                    day_result.trades.append(trade)
                    direction = None

        # Hard close at 16:30 if still holding
        if direction is not None and session_bars:
            last_price = round(session_bars[-1][1]["Close"], 1)
            if direction == "LONG":
                pnl = round(last_price - entry_price, 1)
            else:
                pnl = round(entry_price - last_price, 1)

            trade = Trade(
                date=str(trade_date), day_of_week=day_name,
                bar_type=resolved_type, direction=direction,
                entry_price=entry_price, exit_price=last_price,
                pnl_pts=pnl, mfe_pts=round(mfe, 1), mae_pts=round(mae, 1),
                held_bars=len(session_bars) - entry_bar_idx, held_to_close=True,
                stop_phase=stop_phase, bar_width=width, stake=stake,
                bar_open=o, bar_high=h, bar_low=l, bar_close=c,
                prev_day_dir=prev_day_dir, gap_dir=gap_dir, gap_size=gap_size,
            )
            day_result.trades.append(trade)

        day_result.total_pnl = round(sum(t.pnl_pts for t in day_result.trades), 1)
        day_result.triggered = len(day_result.trades) > 0
        results.append(day_result)
        prev_close = day_df.iloc[-1]["Close"]

    return results


# ==============================================================================
#  VARIANT: Simple candle trail (like ASRS Original)
# ==============================================================================

def run_backtest_candle_trail(
    df: pd.DataFrame,
    doji_action: str = "SKIP",
    buffer_pts: float = BUFFER_PTS,
) -> list[DayResult]:
    """
    Alternative: trail using previous candle low/high instead of
    the 3-phase breakeven/trailing system.
    """
    results = []
    prev_close = 0.0
    trading_days = sorted(set(df.index.date))

    for trade_date in trading_days:
        day_df = df[df.index.date == trade_date]
        if len(day_df) < 5 or trade_date.weekday() >= 5:
            prev_close = day_df.iloc[-1]["Close"] if not day_df.empty else prev_close
            continue

        day_name = trade_date.strftime("%A")

        # Find 08:00 bar
        first_bar = None
        for idx, row in day_df.iterrows():
            if idx.hour == 8 and idx.minute in (0, 5):
                first_bar = row
                break
            if idx.hour >= 8 and first_bar is None:
                first_bar = row
                break

        if first_bar is None:
            prev_close = day_df.iloc[-1]["Close"]
            continue

        o, h, l, c = (round(first_bar["Open"], 1), round(first_bar["High"], 1),
                       round(first_bar["Low"], 1), round(first_bar["Close"], 1))
        width = round(h - l, 1)
        bar_type = classify_bar(o, h, l, c)

        gap_dir, gap_size = classify_gap(prev_close, o) if prev_close > 0 else ("FLAT", 0)

        day_result = DayResult(
            date=str(trade_date), trade_date=trade_date,
            day_of_week=day_name, bar_type=bar_type,
            bar_width=width, bar_open=o, bar_high=h, bar_low=l, bar_close=c,
            gap_dir=gap_dir, gap_size=gap_size,
        )

        resolved_type = bar_type
        if bar_type == "DOJI":
            if doji_action == "SKIP":
                day_result.skipped = True
                results.append(day_result)
                prev_close = day_df.iloc[-1]["Close"]
                continue
            elif doji_action == "TREAT_AS_1BN":
                resolved_type = "1BN"
            elif doji_action == "TREAT_AS_1BP":
                resolved_type = "1BP"

        buy_level = round(l - buffer_pts, 1)
        sell_level = round(h + buffer_pts, 1)
        day_result.buy_level = buy_level
        day_result.sell_level = sell_level

        if resolved_type == "1BN":
            place_buy, place_sell = True, True
        else:
            place_buy, place_sell = False, True
            sell_level = buy_level

        first_bar_idx_loc = day_df.index.get_loc(first_bar.name)
        if isinstance(first_bar_idx_loc, slice):
            first_bar_idx_loc = first_bar_idx_loc.start
        post_bars = list(day_df.iloc[first_bar_idx_loc + 1:].iterrows())

        session_bars = []
        for idx, row in post_bars:
            if idx.hour > 16 or (idx.hour == 16 and idx.minute > 25):
                break
            session_bars.append((idx, row))

        direction = None
        entry_price = 0.0
        trail_stop = 0.0
        mfe = mae = 0.0
        entry_bar_idx = 0

        for i, (idx, row) in enumerate(session_bars):
            if direction is None:
                triggered = False
                if place_buy and row["High"] >= buy_level and place_sell and row["Low"] <= sell_level:
                    if abs(row["Open"] - buy_level) < abs(row["Open"] - sell_level):
                        direction, entry_price = "LONG", buy_level
                    else:
                        direction, entry_price = "SHORT", sell_level
                    triggered = True
                elif place_buy and row["High"] >= buy_level:
                    direction, entry_price = "LONG", buy_level
                    triggered = True
                elif place_sell and row["Low"] <= sell_level:
                    direction, entry_price = "SHORT", sell_level
                    triggered = True

                if triggered:
                    trail_stop = round(l - buffer_pts, 1) if direction == "LONG" else round(h + buffer_pts, 1)
                    mfe = mae = 0.0
                    entry_bar_idx = i
                    continue

            if direction == "LONG":
                mfe = max(mfe, row["High"] - entry_price)
                mae = max(mae, entry_price - row["Low"])

                # Trail to previous candle low
                if i > entry_bar_idx:
                    prev_low = round(session_bars[i - 1][1]["Low"], 1)
                    if prev_low > trail_stop:
                        trail_stop = prev_low

                if row["Low"] <= trail_stop:
                    pnl = round(trail_stop - entry_price, 1)
                    day_result.trades.append(Trade(
                        date=str(trade_date), day_of_week=day_name,
                        bar_type=resolved_type, direction="LONG",
                        entry_price=entry_price, exit_price=trail_stop,
                        pnl_pts=pnl, mfe_pts=round(mfe, 1), mae_pts=round(mae, 1),
                        held_bars=i - entry_bar_idx, stop_phase="CANDLE_TRAIL",
                        bar_width=width, bar_open=o, bar_high=h, bar_low=l, bar_close=c,
                        gap_dir=gap_dir, gap_size=gap_size,
                    ))
                    direction = None

            elif direction == "SHORT":
                mfe = max(mfe, entry_price - row["Low"])
                mae = max(mae, row["High"] - entry_price)

                if i > entry_bar_idx:
                    prev_high = round(session_bars[i - 1][1]["High"], 1)
                    if prev_high < trail_stop:
                        trail_stop = prev_high

                if row["High"] >= trail_stop:
                    pnl = round(entry_price - trail_stop, 1)
                    day_result.trades.append(Trade(
                        date=str(trade_date), day_of_week=day_name,
                        bar_type=resolved_type, direction="SHORT",
                        entry_price=entry_price, exit_price=trail_stop,
                        pnl_pts=pnl, mfe_pts=round(mfe, 1), mae_pts=round(mae, 1),
                        held_bars=i - entry_bar_idx, stop_phase="CANDLE_TRAIL",
                        bar_width=width, bar_open=o, bar_high=h, bar_low=l, bar_close=c,
                        gap_dir=gap_dir, gap_size=gap_size,
                    ))
                    direction = None

        # Hard close at 16:30
        if direction is not None and session_bars:
            last_price = round(session_bars[-1][1]["Close"], 1)
            pnl = round((last_price - entry_price) if direction == "LONG" else (entry_price - last_price), 1)
            day_result.trades.append(Trade(
                date=str(trade_date), day_of_week=day_name,
                bar_type=resolved_type, direction=direction,
                entry_price=entry_price, exit_price=last_price,
                pnl_pts=pnl, mfe_pts=round(mfe, 1), mae_pts=round(mae, 1),
                held_bars=len(session_bars) - entry_bar_idx, held_to_close=True,
                stop_phase="SESSION_CLOSE", bar_width=width,
                bar_open=o, bar_high=h, bar_low=l, bar_close=c,
                gap_dir=gap_dir, gap_size=gap_size,
            ))

        day_result.total_pnl = round(sum(t.pnl_pts for t in day_result.trades), 1)
        day_result.triggered = len(day_result.trades) > 0
        results.append(day_result)
        prev_close = day_df.iloc[-1]["Close"]

    return results


# ==============================================================================
#  OUTPUT / REPORTING
# ==============================================================================

def print_summary(results: list[DayResult], label: str = "FTSE 1BN/1BP"):
    """Print overall backtest summary."""
    all_trades = [t for r in results for t in r.trades]
    triggered_days = [r for r in results if r.triggered]
    skipped_days = [r for r in results if r.skipped]
    win_trades = [t for t in all_trades if t.pnl_pts > 0]
    lose_trades = [t for t in all_trades if t.pnl_pts < 0]

    if not all_trades:
        print("No trades generated.")
        return

    total_pnl = sum(t.pnl_pts for t in all_trades)
    total_gbp = sum(t.pnl_pts * t.stake for t in all_trades)
    win_days = [r for r in results if r.total_pnl > 0]
    lose_days = [r for r in results if r.total_pnl < 0]
    held_to_close = [t for t in all_trades if t.held_to_close]

    # Bar type breakdown
    bn_trades = [t for t in all_trades if t.bar_type == "1BN"]
    bp_trades = [t for t in all_trades if t.bar_type == "1BP"]

    # Streaks
    max_win_streak = max_lose_streak = 0
    cur_win = cur_lose = 0
    for r in triggered_days:
        if r.total_pnl > 0:
            cur_win += 1; cur_lose = 0
            max_win_streak = max(max_win_streak, cur_win)
        elif r.total_pnl < 0:
            cur_lose += 1; cur_win = 0
            max_lose_streak = max(max_lose_streak, cur_lose)
        else:
            cur_win = cur_lose = 0

    # Drawdown
    equity = []
    running = 0
    peak = max_dd = 0
    for r in results:
        running += r.total_pnl
        equity.append(running)
        peak = max(peak, running)
        max_dd = max(max_dd, peak - running)

    # Monthly count
    months = set(r.date[:7] for r in results)

    avg_win = round(np.mean([t.pnl_pts for t in win_trades]), 1) if win_trades else 0
    avg_loss = round(np.mean([t.pnl_pts for t in lose_trades]), 1) if lose_trades else 0

    print(f"""
================================================================================
  {label} BACKTEST RESULTS
================================================================================
  Period:      {results[0].date} -> {results[-1].date}
  Days:        {len(results)} total, {len(triggered_days)} triggered, {len(skipped_days)} doji skipped
--------------------------------------------------------------------------------
  TRADES
  Total:       {len(all_trades)}
  Winners:     {len(win_trades)} ({round(len(win_trades)/len(all_trades)*100)}%)
  Losers:      {len(lose_trades)} ({round(len(lose_trades)/len(all_trades)*100)}%)
  Avg win:     {avg_win:+.1f} pts
  Avg loss:    {avg_loss:+.1f} pts
  Best trade:  {max(t.pnl_pts for t in all_trades):+.1f} pts
  Worst trade: {min(t.pnl_pts for t in all_trades):+.1f} pts
  Held to 16:30: {len(held_to_close)} ({round(len(held_to_close)/len(all_trades)*100)}%)
--------------------------------------------------------------------------------
  BAR TYPE BREAKDOWN
  1BN trades:  {len(bn_trades)} -> P&L: {sum(t.pnl_pts for t in bn_trades):+.1f} pts (avg {round(np.mean([t.pnl_pts for t in bn_trades]),1) if bn_trades else 0:+.1f})
  1BP trades:  {len(bp_trades)} -> P&L: {sum(t.pnl_pts for t in bp_trades):+.1f} pts (avg {round(np.mean([t.pnl_pts for t in bp_trades]),1) if bp_trades else 0:+.1f})
--------------------------------------------------------------------------------
  DAYS
  Win days:    {len(win_days)} ({round(len(win_days)/len(triggered_days)*100) if triggered_days else 0}%)
  Lose days:   {len(lose_days)} ({round(len(lose_days)/len(triggered_days)*100) if triggered_days else 0}%)
  Best day:    {max(r.total_pnl for r in results):+.1f} pts
  Worst day:   {min(r.total_pnl for r in results):+.1f} pts
--------------------------------------------------------------------------------
  P&L
  Total:       {total_pnl:+.1f} pts (GBP {total_gbp:+.1f} at variable stake)
  Daily avg:   {round(total_pnl / len(triggered_days), 1) if triggered_days else 0:+.1f} pts
  Monthly avg: ~{round(total_pnl / max(1, len(months)), 1):+.1f} pts/month
--------------------------------------------------------------------------------
  RISK
  Max DD:      {max_dd:.1f} pts
  Win streak:  {max_win_streak} days
  Lose streak: {max_lose_streak} days
  Avg MFE:     {round(np.mean([t.mfe_pts for t in all_trades]), 1):.1f} pts
  Avg MAE:     {round(np.mean([t.mae_pts for t in all_trades]), 1):.1f} pts
  Avg bars:    {round(np.mean([t.held_bars for t in all_trades]), 1):.1f}
--------------------------------------------------------------------------------
  SCALING (at GBP 1/pt)
  1  per pt:   GBP {total_pnl:+,.0f}
  2  per pt:   GBP {total_pnl * 2:+,.0f}
  5  per pt:   GBP {total_pnl * 5:+,.0f}
  10 per pt:   GBP {total_pnl * 10:+,.0f}
================================================================================
""")

    # Monthly breakdown
    print("-- Monthly Breakdown -------------------------------------------------------")
    print(f"{'Month':<10} {'Days':>5} {'Trades':>7} {'Win%':>6} {'P&L':>8} {'Cum':>8}")
    print("-" * 55)

    monthly = defaultdict(lambda: {"days": 0, "trades": 0, "wins": 0, "pnl": 0})
    for r in results:
        m = r.date[:7]
        monthly[m]["days"] += 1
        monthly[m]["trades"] += len(r.trades)
        monthly[m]["wins"] += sum(1 for t in r.trades if t.pnl_pts > 0)
        monthly[m]["pnl"] += r.total_pnl

    cum = 0
    for m in sorted(monthly.keys()):
        d = monthly[m]
        cum += d["pnl"]
        wr = round(d["wins"] / d["trades"] * 100) if d["trades"] else 0
        print(f"{m:<10} {d['days']:>5} {d['trades']:>7} {wr:>5}% {d['pnl']:>+7.1f} {cum:>+7.1f}")


def print_situational(results: list[DayResult]):
    """Breakdown by bar type, day of week, gap direction."""
    all_trades = [t for r in results for t in r.trades]
    if not all_trades:
        print("No trades to analyse.")
        return

    def _section(title, key_fn):
        groups = defaultdict(list)
        for t in all_trades:
            groups[key_fn(t)].append(t)

        print(f"\n-- {title} " + "-" * (60 - len(title)))
        print(f"{'Category':<15} {'Trades':>7} {'Win%':>6} {'AvgW':>7} {'AvgL':>7} {'Total':>8} {'Avg':>7}")
        print("-" * 65)
        for k in sorted(groups.keys()):
            trades = groups[k]
            wins = [t for t in trades if t.pnl_pts > 0]
            losses = [t for t in trades if t.pnl_pts < 0]
            total = sum(t.pnl_pts for t in trades)
            wr = round(len(wins) / len(trades) * 100) if trades else 0
            avg_w = round(np.mean([t.pnl_pts for t in wins]), 1) if wins else 0
            avg_l = round(np.mean([t.pnl_pts for t in losses]), 1) if losses else 0
            avg = round(total / len(trades), 1)
            print(f"{k:<15} {len(trades):>7} {wr:>5}% {avg_w:>+6.1f} {avg_l:>+6.1f} {total:>+7.1f} {avg:>+6.1f}")

    print(f"""
================================================================================
  FTSE SITUATIONAL ANALYSIS
  "When does the strategy work best?"
================================================================================""")

    _section("Bar Type", lambda t: t.bar_type)
    _section("Direction", lambda t: t.direction)
    _section("Day of Week", lambda t: t.day_of_week)
    _section("Gap Direction", lambda t: t.gap_dir or "N/A")
    _section("Stop Phase", lambda t: t.stop_phase)
    _section("Bar Width", lambda t: "NARROW(<15)" if t.bar_width < 15 else ("WIDE(>30)" if t.bar_width > 30 else "NORMAL"))
    _section("Prev Day", lambda t: t.prev_day_dir or "N/A")
    _section("Bar Type+Dir", lambda t: f"{t.bar_type}_{t.direction}")


def generate_charts(results: list[DayResult], label: str = "FTSE 1BN/1BP"):
    """Generate equity curve, drawdown, and distribution charts."""
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        import matplotlib.dates as mdates
    except ImportError:
        logger.warning("matplotlib not available -- skipping charts")
        return

    all_trades = [t for r in results for t in r.trades]
    if not all_trades:
        return

    chart_dir = os.path.join(DATA_DIR, "charts")
    os.makedirs(chart_dir, exist_ok=True)

    # Equity curve
    dates = []
    equity = []
    running = 0
    for r in results:
        running += r.total_pnl
        if r.triggered:
            dates.append(datetime.strptime(r.date, "%Y-%m-%d"))
            equity.append(running)

    fig, axes = plt.subplots(2, 2, figsize=(16, 10))
    fig.suptitle(f"{label} Backtest Results", fontsize=16, fontweight="bold")

    # Equity curve
    ax = axes[0, 0]
    ax.plot(dates, equity, color="#2196F3", linewidth=1.5)
    ax.axhline(y=0, color="gray", linewidth=0.5, linestyle="--")
    ax.set_title("Equity Curve")
    ax.set_ylabel("Cumulative P&L (pts)")
    ax.grid(True, alpha=0.3)

    # Drawdown
    ax = axes[0, 1]
    peak = 0
    dd_vals = []
    for e in equity:
        peak = max(peak, e)
        dd_vals.append(peak - e)
    ax.fill_between(dates, dd_vals, color="#f44336", alpha=0.4)
    ax.set_title("Drawdown")
    ax.set_ylabel("Drawdown (pts)")
    ax.grid(True, alpha=0.3)

    # P&L distribution
    ax = axes[1, 0]
    pnls = [t.pnl_pts for t in all_trades]
    colors = ["#4CAF50" if p >= 0 else "#f44336" for p in pnls]
    ax.hist(pnls, bins=50, color="#2196F3", edgecolor="white", alpha=0.8)
    ax.axvline(x=0, color="gray", linewidth=1)
    ax.set_title("P&L Distribution")
    ax.set_xlabel("P&L (pts)")

    # Monthly P&L
    ax = axes[1, 1]
    monthly = defaultdict(float)
    for r in results:
        monthly[r.date[:7]] += r.total_pnl
    months = sorted(monthly.keys())
    vals = [monthly[m] for m in months]
    colors = ["#4CAF50" if v >= 0 else "#f44336" for v in vals]
    ax.bar(range(len(months)), vals, color=colors)
    ax.set_xticks(range(len(months)))
    ax.set_xticklabels(months, rotation=45, fontsize=7)
    ax.set_title("Monthly P&L")
    ax.set_ylabel("P&L (pts)")
    ax.grid(True, alpha=0.3, axis="y")

    plt.tight_layout()
    path = os.path.join(chart_dir, "ftse_backtest.png")
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"\nChart saved to {path}")


def export_trades(results: list[DayResult], path: str = None):
    """Export all trades to CSV."""
    if path is None:
        path = os.path.join(DATA_DIR, "ftse_backtest_trades.csv")

    all_trades = [t for r in results for t in r.trades]
    if not all_trades:
        print("No trades to export.")
        return

    fields = [
        "date", "day_of_week", "bar_type", "direction",
        "entry_price", "exit_price", "pnl_pts", "mfe_pts", "mae_pts",
        "held_bars", "held_to_close", "stop_phase",
        "bar_width", "stake", "bar_open", "bar_high", "bar_low", "bar_close",
        "gap_dir", "gap_size", "prev_day_dir",
    ]
    with open(path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        for t in all_trades:
            writer.writerow({k: getattr(t, k, "") for k in fields})

    print(f"Exported {len(all_trades)} trades to {path}")


def compare_variants(df: pd.DataFrame):
    """Compare 3-phase stop vs simple candle trail."""
    print("\nRunning 3-phase stop backtest...")
    r1 = run_backtest(df)
    print("Running candle trail backtest...")
    r2 = run_backtest_candle_trail(df)

    t1 = [t for r in r1 for t in r.trades]
    t2 = [t for r in r2 for t in r.trades]

    def stats(trades):
        pnl = sum(t.pnl_pts for t in trades)
        wins = [t for t in trades if t.pnl_pts > 0]
        losses = [t for t in trades if t.pnl_pts < 0]
        wr = round(len(wins) / len(trades) * 100, 1) if trades else 0
        avg_w = round(np.mean([t.pnl_pts for t in wins]), 1) if wins else 0
        avg_l = round(np.mean([t.pnl_pts for t in losses]), 1) if losses else 0
        eq = []
        r = 0
        for t in trades:
            r += t.pnl_pts
            eq.append(r)
        pk = dd = 0
        for e in eq:
            pk = max(pk, e)
            dd = max(dd, pk - e)
        return {"n": len(trades), "pnl": pnl, "wr": wr, "avg_w": avg_w, "avg_l": avg_l, "dd": dd}

    s1 = stats(t1)
    s2 = stats(t2)

    print(f"""
================================================================================
  FTSE: 3-Phase Stop vs Candle Trail Comparison
================================================================================
                    {'3-Phase':>12}  {'Candle Trail':>12}
  Trades:           {s1['n']:>12}  {s2['n']:>12}
  Win rate:         {s1['wr']:>11}%  {s2['wr']:>11}%
  Avg win:          {s1['avg_w']:>+11.1f}  {s2['avg_w']:>+11.1f}
  Avg loss:         {s1['avg_l']:>+11.1f}  {s2['avg_l']:>+11.1f}
  Total P&L:        {s1['pnl']:>+11.1f}  {s2['pnl']:>+11.1f}
  Max DD:           {s1['dd']:>11.1f}  {s2['dd']:>11.1f}
================================================================================
""")


# ==============================================================================
#  MAIN
# ==============================================================================

def main():
    args = sys.argv[1:] if len(sys.argv) > 1 else []

    df, all_df = load_data()
    if df is None:
        print("No FTSE data found. Run fetch_ftse.py first to download from IBKR.")
        print(f"Expected at: {os.path.join(DATA_DIR, 'ftse_rth.parquet')}")
        print(f"         or: {os.path.join(DATA_DIR, 'ftse_all.parquet')}")
        return

    # Use all_df if available (includes pre-market 08:00 bar)
    data = all_df if all_df is not None else df

    print(f"Data: {len(data)} bars, {data.index[0]} -> {data.index[-1]}")

    # Month filter
    month_filter = ""
    if "--month" in args:
        idx = args.index("--month")
        if idx + 1 < len(args):
            month_filter = args[idx + 1]

    if "--compare" in args:
        compare_variants(data)
        return

    # Run default backtest
    results = run_backtest(data)

    if month_filter:
        results = [r for r in results if r.date.startswith(month_filter)]

    if "--situational" in args:
        print_summary(results)
        print_situational(results)
    elif "--export" in args:
        print_summary(results)
        export_trades(results)
    elif "--charts" in args:
        print_summary(results)
        generate_charts(results)
    else:
        print_summary(results)

    if "--charts" in args or len(args) == 0:
        try:
            generate_charts(results)
        except Exception as e:
            logger.warning(f"Chart generation failed: {e}")


if __name__ == "__main__":
    main()
