"""
rules.py — Situational Rules Engine
═══════════════════════════════════════════════════════════════════════════════

Loads actionable rules from backtest situational analysis.
Classifies today's conditions and returns a confidence verdict:

    AUTO_TRADE   → Strong edge, place orders automatically
    ASK_HUMAN    → Ambiguous, send Telegram with buttons
    AUTO_SKIP    → Negative edge, send info-only alert

Rules are stored as JSON, generated by running:
    python backtest.py --generate-rules

Can also be manually edited to add/override rules.
"""

import os
import json
import logging
from dataclasses import dataclass
from datetime import datetime

from dax_bot import config

logger = logging.getLogger(__name__)

RULES_FILE = os.path.join(os.path.dirname(__file__), "data", "dax", "situational_rules.json")

# ── Confidence Levels ──────────────────────────────────────────────────────────

class Verdict:
    AUTO_TRADE  = "AUTO_TRADE"
    ASK_HUMAN   = "ASK_HUMAN"
    AUTO_SKIP   = "AUTO_SKIP"


# ── Default rules (used if no backtest rules file exists yet) ──────────────────

DEFAULT_RULES = {
    "trade_rules": [],       # Populated by backtest
    "skip_rules": [],        # Populated by backtest
    "min_sample": 5,         # Minimum trades to trust a rule
    "trade_threshold": {
        "min_win_rate": 55,
        "min_avg_pnl": 2.0,
    },
    "skip_threshold": {
        "max_win_rate": 40,
        "max_avg_pnl": -2.0,
    },
    "default_action": "ASK_HUMAN",   # When no rule matches
    "no_response_action": "SKIP",    # SKIP or TRADE — what to do if human doesn't respond
    "response_timeout_sec": 300,     # 5 minutes to respond
}


@dataclass
class TodayConditions:
    """Today's situational tags, matching backtest Trade fields."""
    day_of_week:   str = ""      # Monday, Tuesday, etc.
    gap_dir:       str = ""      # GAP_UP, GAP_DOWN, FLAT
    gap_size:      float = 0.0
    range_class:   str = ""      # NARROW, NORMAL, WIDE
    context:       str = ""      # DIRECTIONAL, CHOPPY, OVERLAP, MIXED
    bar_bullish:   bool = False
    prev_day_dir:  str = ""      # UP, DOWN
    overnight_bias: str = ""     # SHORT_ONLY, LONG_ONLY, STANDARD, NO_DATA

    def combos(self) -> list[str]:
        """Generate all condition combos to match against rules."""
        day = self.day_of_week[:3]
        bar_char = "BULL" if self.bar_bullish else "BEAR"
        ov = self.overnight_bias or "NO_DATA"
        return [
            # Single conditions
            self.day_of_week,
            self.gap_dir,
            self.range_class,
            self.context,
            ov,

            # Cross-tabulations (must match backtest.py slicer format)
            f"{day} + {self.gap_dir}",
            f"{day} + LONG",
            f"{day} + SHORT",
            f"{self.gap_dir} + {self.range_class}",
            f"{self.gap_dir} + {self.context}",
            f"{self.gap_dir} + {bar_char} bar",
            f"{self.context} + {self.range_class}",
            f"Prev:{self.prev_day_dir} + {self.gap_dir}",
            # V58 overnight combos
            f"{ov} + LONG",
            f"{ov} + SHORT",
            f"{ov} + {self.gap_dir}",
            f"{ov} + {day}",
            f"{ov} + {self.context}",
            f"{ov} + {self.range_class}",
        ]

    def summary_str(self) -> str:
        """Human-readable summary."""
        ov = self.overnight_bias or "N/A"
        return (
            f"{self.day_of_week} | {self.gap_dir} ({self.gap_size:+.0f}pts) | "
            f"{self.range_class} range | {self.context} | "
            f"Bar4: {'bullish' if self.bar_bullish else 'bearish'} | "
            f"V58: {ov}"
        )


@dataclass
class RuleMatch:
    """Result of checking conditions against rules."""
    verdict:       str = Verdict.ASK_HUMAN
    matching_rules: list = None
    best_rule:     dict = None
    confidence:    str = ""       # Description for Telegram
    stats:         str = ""       # Stats summary

    def __post_init__(self):
        if self.matching_rules is None:
            self.matching_rules = []


# ── Rules Engine ───────────────────────────────────────────────────────────────

def load_rules() -> dict:
    """Load rules from disk, or return defaults."""
    if os.path.exists(RULES_FILE):
        try:
            with open(RULES_FILE) as f:
                rules = json.load(f)
            logger.info(f"Loaded {len(rules.get('trade_rules', []))} TRADE rules, "
                       f"{len(rules.get('skip_rules', []))} SKIP rules")
            return rules
        except Exception as e:
            logger.error(f"Failed to load rules: {e}")
    logger.info("No rules file — using defaults (ASK_HUMAN for everything)")
    return DEFAULT_RULES.copy()


def save_rules(rules: dict):
    """Save rules to disk."""
    os.makedirs(os.path.dirname(RULES_FILE), exist_ok=True)
    with open(RULES_FILE, "w") as f:
        json.dump(rules, f, indent=2)
    logger.info(f"Saved rules to {RULES_FILE}")


def evaluate(conditions: TodayConditions) -> RuleMatch:
    """
    Check today's conditions against stored rules.
    Returns verdict: AUTO_TRADE, ASK_HUMAN, or AUTO_SKIP.
    """
    rules = load_rules()
    combos = conditions.combos()

    # Check SKIP rules first (safety first)
    skip_matches = []
    for rule in rules.get("skip_rules", []):
        if rule["combo"] in combos:
            skip_matches.append(rule)

    if skip_matches:
        best = max(skip_matches, key=lambda r: r.get("sample", 0))
        return RuleMatch(
            verdict=Verdict.AUTO_SKIP,
            matching_rules=skip_matches,
            best_rule=best,
            confidence=f"❌ SKIP — backtest says avoid",
            stats=(
                f"Rule: [{best['combo']}]\n"
                f"Sample: {best.get('sample', '?')} trades\n"
                f"Win rate: {best.get('win_rate', '?')}%\n"
                f"Avg P&L: {best.get('avg_pnl', '?'):+.1f} pts"
            ),
        )

    # Check TRADE rules
    trade_matches = []
    for rule in rules.get("trade_rules", []):
        if rule["combo"] in combos:
            trade_matches.append(rule)

    if trade_matches:
        best = max(trade_matches, key=lambda r: r.get("avg_pnl", 0))
        return RuleMatch(
            verdict=Verdict.AUTO_TRADE,
            matching_rules=trade_matches,
            best_rule=best,
            confidence=f"✅ TRADE — backtest edge confirmed",
            stats=(
                f"Rule: [{best['combo']}]\n"
                f"Sample: {best.get('sample', '?')} trades\n"
                f"Win rate: {best.get('win_rate', '?')}%\n"
                f"Avg P&L: {best.get('avg_pnl', '?'):+.1f} pts"
            ),
        )

    # No matching rules
    default = rules.get("default_action", "ASK_HUMAN")
    return RuleMatch(
        verdict=default,
        confidence="⚠️ No matching rule — your call",
        stats=f"Conditions: {conditions.summary_str()}",
    )


def build_conditions_from_state(state, prev_close: float = 0) -> TodayConditions:
    """Build TodayConditions from a DailyState object."""
    now = datetime.now(config.TZ_UK)
    gap_dir = "FLAT"
    gap_size = 0
    if prev_close > 0:
        gap_size = round(state.bar_high - prev_close, 1)  # Approximate
        if gap_size > 10:
            gap_dir = "GAP_UP"
        elif gap_size < -10:
            gap_dir = "GAP_DOWN"

    return TodayConditions(
        day_of_week=now.strftime("%A"),
        gap_dir=gap_dir,
        gap_size=gap_size,
        range_class=state.range_flag or "NORMAL",
        context="DIRECTIONAL" if state.context_directional else
                "CHOPPY" if state.context_choppy else
                "OVERLAP" if state.context_overlap else "MIXED",
        bar_bullish=state.bar_high > state.bar_low,
        prev_day_dir="",
        overnight_bias=state.overnight_bias or "NO_DATA",
    )


# ── Rule Generation (called from backtest) ─────────────────────────────────────

def generate_rules_from_backtest(all_trades: list, min_sample: int = 5) -> dict:
    """
    Analyse backtest trades and generate situational rules.
    Called by: python backtest.py --generate-rules
    """
    from collections import defaultdict
    import numpy as np

    rules = DEFAULT_RULES.copy()
    rules["trade_rules"] = []
    rules["skip_rules"] = []
    rules["generated_at"] = datetime.now().isoformat()
    rules["total_trades"] = len(all_trades)

    # Define all slicers (must match backtest.py)
    slicers = [
        ("Day + Gap", lambda t: f"{t.day_of_week[:3]} + {t.gap_dir}"),
        ("Day + Direction", lambda t: f"{t.day_of_week[:3]} + {t.direction}"),
        ("Gap + Range", lambda t: f"{t.gap_dir} + {t.range_class}"),
        ("Gap + Context", lambda t: f"{t.gap_dir} + {t.context}"),
        ("Gap + Bar4", lambda t: f"{t.gap_dir} + {'BULL' if t.bar_bullish else 'BEAR'} bar"),
        ("Context + Range", lambda t: f"{t.context} + {t.range_class}"),
        ("Context + Direction", lambda t: f"{t.context} + {t.direction}"),
        ("PrevDay + Gap", lambda t: f"Prev:{t.prev_day_dir or 'N/A'} + {t.gap_dir}"),
        # V58 overnight combos
        ("V58 + Direction", lambda t: f"{t.overnight_bias or 'N/A'} + {t.direction}"),
        ("V58 + Gap", lambda t: f"{t.overnight_bias or 'N/A'} + {t.gap_dir}"),
        ("V58 + Day", lambda t: f"{t.overnight_bias or 'N/A'} + {t.day_of_week[:3]}"),
        ("V58 + Context", lambda t: f"{t.overnight_bias or 'N/A'} + {t.context}"),
        ("V58 + Range", lambda t: f"{t.overnight_bias or 'N/A'} + {t.range_class}"),
    ]

    for slicer_name, slicer_fn in slicers:
        groups = defaultdict(list)
        for t in all_trades:
            groups[slicer_fn(t)].append(t)

        for combo, trades in groups.items():
            n = len(trades)
            if n < min_sample:
                continue

            wins = sum(1 for t in trades if t.pnl_pts > 0)
            avg_pnl = float(np.mean([t.pnl_pts for t in trades]))
            total_pnl = float(sum(t.pnl_pts for t in trades))
            win_rate = round(wins / n * 100)

            rule_entry = {
                "combo": combo,
                "slicer": slicer_name,
                "sample": n,
                "win_rate": win_rate,
                "avg_pnl": round(avg_pnl, 1),
                "total_pnl": round(total_pnl, 1),
            }

            if win_rate >= rules["trade_threshold"]["min_win_rate"] and \
               avg_pnl >= rules["trade_threshold"]["min_avg_pnl"]:
                rules["trade_rules"].append(rule_entry)

            elif win_rate <= rules["skip_threshold"]["max_win_rate"] and \
                 avg_pnl <= rules["skip_threshold"]["max_avg_pnl"]:
                rules["skip_rules"].append(rule_entry)

    # Sort by strength
    rules["trade_rules"].sort(key=lambda r: r["avg_pnl"], reverse=True)
    rules["skip_rules"].sort(key=lambda r: r["avg_pnl"])

    save_rules(rules)

    logger.info(f"Generated {len(rules['trade_rules'])} TRADE rules, "
               f"{len(rules['skip_rules'])} SKIP rules "
               f"from {len(all_trades)} trades")

    return rules
